### ISSUE TITLE
requesting 10.1.2 support

### ISSUE THREAD

**Issue by modusc896d352** [pedro-javierf/NTRGhidra#11]
it's been a while since GHIDRA 10.1.2 has been released and i'm wondering if this extension is going to support it.

honestly, i'm not really able to explain this super well but the short of it is GHIDRA doesn't take it well when it detects an extension that isn't meant to be used on anything other than on that particular GHIDRA version so i'd appreciate it if there was a build with support for 10.1.2 if possible!

**Comment by pedro-javierf** [comment]
@modusc896d352 a new release with support for Ghidra 10.1.2 has been published:
 https://github.com/pedro-javierf/NTRGhidra/releases/tag/v1.4.4.1-ghidra-10.1.2

Please install it and test it and report if all works great for you :)

**Comment by modusc896d352** [comment]
installed it, tested it, and i must report it works really well. thanks!

**Comment by Margen67** [comment]
#13
