### ISSUE TITLE
Release for 10.2.x

### ISSUE THREAD

**Issue by NEPETAISCUTE** [pedro-javierf/NTRGhidra#15]
for now support only exists for ghidra up to 10.1.5, but the last version is ghidra 10.2.2, would it be possible to release a version for the last version of ghidra? which by the way implements a lot of very useful features

**Comment by pedro-javierf** [comment]
Hi, thanks for opening the issue!

It's my aim that the repo provides updated builds from time to time. So far @master801 has been delivering builds for the latest versions too. I'll try to see if I can set up the build environment again in the coming days, but can't promise a date. 

BTW: What would you say are the most useful new features in latest Ghidra? Asking to see if there's something that NTRGhidra could make more use of. Ty!

**Comment by NEPETAISCUTE** [comment]
well since 10.2.0 i think, when you change the reference of a function to a different overlay, it actually allows you to go to that function by double clicking on it, before it used to bring you to the old reference, which usually ended up quite frustrating

accessorily there's debug i think? but i'm not sure it could be used with NTRGhidra since it's centered around gdb and pc debugging, though maybe you could make it link to no$gba or something like that? though i got no idea how difficult it would be to do that

that's all i can think of out of my head sorry-

**Comment by master801** [comment]
no$gba doesn't use GDB but instead some weird proprietary serial driver for the Xboo cable.

DeSmuME does use GDB for debugging, but I can't seem to get it to work. Probably due to inexperience with GDB in general.
`DeSmuME.exe --arm9gdb=7777 --arm7gdb=8888`

Not sure about melonDS, but I would prefer not to use it. I don't think it has GDB debugging, anyway.

**Comment by NEPETAISCUTE** [comment]
ohhh i see, well good to know then

**Comment by pedro-javierf** [comment]
@Margen67 this project is mostly unmaintained / looking for maintainers, and I'm not uploading newer builds myself. Hence, we're always one or two versions behind the latest Ghidra version. I always accept PRs from contributors, though, which is what keeps us updated.

We could probably set up some CI to build for the latest Ghidra releases. Other ideas are welcome too ^^
