### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by NO-ob** [pedro-javierf/NTRGhidra#2]
I cant build as i get an error about the build script using deprecated gradle functions. Could you post a build on the releases page please

**Comment by pedro-javierf** [comment]
Version v1.2 has been added to releases. Let me know if it works correctly or there is any issue

**Comment by NO-ob** [comment]
Thankyou, I'm not sure if its working if I import a .nds or arm7/arm9.bin i get no format option for it other than raw binary

**Comment by pedro-javierf** [comment]
I have just installed it in a clean installation and it works fine. Make sure that:
* You not only copy the .zip but also actually install it
* Restart Ghidra (important)
* You are using Ghidra 9.1.2

It should work for .nds files. There is no direct support for arm7/arm9.bin, as the extension automatically extracts them from the .nds file.

**Comment by NO-ob** [comment]
I put the zip in /Extensions/Ghidra then ticked it in the install extension dialog and restarted. What java version are you using? maybe i'm using a different version

**Comment by pedro-javierf** [comment]
openjdk-12.0.1 x64 bits
Did you press "OK" after ticking the entry in the install extension dialog?

**Comment by NO-ob** [comment]
Thank you its working with java13 i was using 11 before

**Comment by pedro-javierf** [comment]
I'm glad it worked, I close this issue.
