### ISSUE TITLE
Extension version incompatible

### ISSUE THREAD

**Issue by micsthepick** [pedro-javierf/NTRGhidra#3]
**Description**
When attempting to install the extension on Ghidra 9.1.2, it fails, due to the Version tag containing "@1.4@"

    Installation Error: Extension version for [NTRGhidra] is incompatible with Ghidra.

**To Reproduce**
1. Use Ghidra 9.1.2
2. Copy Extension Zip file to [InstallDirectory]/Extensions/Ghidra
3. Open Ghidra
4. File -> Install Extensions
5. Select NTRGhidra

**Expected behavior**
Extension works on 9.1.2, or the required version of Ghidra for the plugin is documented somewhere. I suspect that the Version field does not represent the version of the plugin, rather the version of Ghidra the plugin works for

**Desktop**
 - OS: Windows 10
 - 1909

**Comment by pedro-javierf** [comment]
I have updated 1.4.1 release with the fixed extension.properties

**Comment by micsthepick** [comment]
I was able to build from source, and the extension now installs correctly. You might want to create a new release, but I will close this issue
