### ISSUE TITLE
Duplicate labels - differentiate somehow?

### ISSUE THREAD

**Issue by sudofox** [pedro-javierf/NTRGhidra#4]
In some cases we have duplicate symbol labels, for example, REG_DISPCNT/REG_DISPSTAT/REG_MASTER_BRIGHT, split between ARM9 Display Engine A and B. Is there a good way to differentiate these?

Note that I had to manually import the symbol labels due to some incompatibilities here and there with the loader and DSi apps. I suppose I could suffix them with _A and _B or something like that, but I'm still a bit new to Ghidra.

Cheers

**Comment by pedro-javierf** [comment]
Indeed the names are repeated, good find! I believe you should be able to rename then manually to _A or _B in the meantime (left click in the view). Nevertheless I will make sure to update the names to differentiate them and build a new release.

DSi apps are not fully supported yet, I have the DSi labels and new memory regions waiting to be merged but the actual loader code for arm7i and arm9i is what is left to be programmed

**Comment by pedro-javierf** [comment]
This is now corrected with commit aaea039

I've chosen to use the following convention: 

- REG_A_DISPCNT
- REG_B_DISPCNT

To differentiate between the REGister from Display Engine A and B. I'll upload a new release with this change.

Should there be any error or missing [register](http://problemkaputt.de/gbatek.htm#dsiomaps) don't hesitate to open another issue or pull request!

**Comment by sudofox** [comment]
Thanks much!
