### ISSUE TITLE
10.0 support

### ISSUE THREAD

**Issue by XLuma** [pedro-javierf/NTRGhidra#9]
**Describe the solution you'd like**
I'd like to see support for later versions of Gihdra. 9.2.2 does not have a gdb stub, while later versions do, and being able to debug NDS programs remotely is extremely powerful.

**Describe alternatives you've considered**
IDA, but the price is kind of a setback.

**Additional context**
10.0 would be nice :D

**Comment by pedro-javierf** [comment]
Thanks for opening an issue! 
NTRGhidra is definitely getting 10.0 support in the next couple of months. There are other new work-in-progress features and bug-fixes that will be included with such release once everything is ready

**Comment by martmists-gh** [comment]
Any updates on this?

**Comment by pedro-javierf** [comment]
> Any updates on this?

Thanks for your interest @martmists-gh 
I've been **looking to add people that want to contribute to the project,** as I don't have any time to maintain it for now. I will try to generate a build for the latest release anyways asap

**Comment by pedro-javierf** [comment]
@XLuma @martmists-gh the [latest release](https://github.com/pedro-javierf/NTRGhidra/releases/tag/v1.4.4.1) adds support for Ghidra 10.0.4 👍
